# Generated by Django 5.0.7 on 2024-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
